### ISSUE TITLE
When generate the zpm module use ${dbrole} instead current settings

### ISSUE THREAD

**Issue by evshvarov** [intersystems/ipm#149]
Now if you generate it sets the security resource for the app to the current namespace value, e.g. MatchRoles=":%DB_COFFEE" 
But better use the variable, like here:
MatchRoles=":${dbrole}"

**Comment by SergeyMi37** [comment]
/// adds a web application to the temporary array of module resources
Method AddWebApps(pApps As %String, Output cspapps As %List) As %Status
{
    Set tAppList = ""
    Set pApps = $ZSTRIP(pApps,"<>W")
    If ( pApps = "*" ) {
	    Do ..GetCSPApplications(.tAppList)
    } Else { 
        Set tAppList = $Listfromstring(pApps,",")
    }
    Set cspapps = ""
    New $Namespace
    Set $Namespace = "%SYS"
    For i=1:1:$Listlength(tAppList) {
        Set app = ##class(Security.Applications).Get($Listget(tAppList,i),.props)
        Set tAppName = props("Name")
        Set ..TemplateResources(tAppName) = tAppName
        Set ..TemplateResources(tAppName, "Url") = tAppName
 
        If (props("DispatchClass")'="") {
            Set ..TemplateResources(tAppName,"DispatchClass") = props("DispatchClass") 
        } Else {
            Set tCSPDir = ##class(%File).NormalizeDirectory(##class(%File).ParentDirectoryName(##class(%File).ManagerDirectory())_"/csp")
            Set ..TemplateResources(tAppName,"Directory") = $Replace(props("Path"),tCSPDir,"${cspdir}")
            Set cspapps = cspapps_$Listbuild(tAppName)
            
        }
        If ( props("AutheEnabled") = 32 ) {
            Set ..TemplateResources(tAppName,"UnauthenticatedEnabled") = 0
            Set ..TemplateResources(tAppName,"PasswordAuthEnabled") = 1
        } ElseIf ( props("AutheEnabled") = 64 ) {
            Set ..TemplateResources(tAppName,"UnauthenticatedEnabled") = 0
            Set ..TemplateResources(tAppName,"PasswordAuthEnabled") = 1            
        } ElseIf ( props("AutheEnabled") = 96 ) {
            Set ..TemplateResources(tAppName,"UnauthenticatedEnabled") = 1
            Set ..TemplateResources(tAppName,"PasswordAuthEnabled") = 1            
        } Else {
            Set ..TemplateResources(tAppName,"AuthenticationMethods") = props("AutheEnabled")
        }

        // Map subscript of application properties to %Installer.CSPApplication properties 
        Set tMap("AutoCompile") = "AutoCompile"
        Set tMap("AutoCompile","default") = 1
        Set tMap("Enabled") = "Enabled"
        Set tMap("Enabled","default") = 1        
        Set tMap("ChangePasswordPage") = "ChangePasswordPage" 
        Set tMap("ErrorPage") = "CustomErrorPage" 
        Set tMap("SuperClass") = "DefaultSuperclass" 
        Set tMap("Timeout") = "DefaultTimeout" 
        Set tMap("Description") = "Description" 
        Set tMap("EventClass") = "EventClass" 
        Set tMap("MatchRoles") = "MatchRoles" 
        Set tMap("GroupById") = "GroupById" 
        Set tMap("InbndWebServicesEnabled") = "InboundWebServicesEnabled" 
        Set tMap("InbndWebServicesEnabled","default") = 1
        Set tMap("IsNamespaceDefault") = "IsNamespaceDefault" 
        Set tMap("IsNamespaceDefault","default") = 0
        Set tMap("LockCSPName") = "LockCSPName" 
        Set tMap("LockCSPName","default") = 1
        Set tMap("LoginPage") = "LoginClass" 
        Set tMap("Package") = "PackageName" 
        Set tMap("CookiePath") = "CookiePath" 
        Set tMap("UseCookies") = "UseSessionCookie" 
        Set tMap("PermittedClasses") = "PermittedClasses" 
        Set tMap("Recurse") = "Recurse" 
        Set tMap("Recurse","default") = 0
        Set tMap("Resource") = "Resource" 
        Set tMap("ServeFiles") = "ServeFiles" 
        Set tMap("ServeFilesTimeout") = "ServeFilesTimeout" 
        Set tMap("TwoFactorEnabled") = "TwoFactorEnabled" 
        Set tMap("TwoFactorEnabled","default") = 0

        Set tAttr = ""
        For {
            Set tAttr = $Order(tMap(tAttr))
            Quit:(tAttr="")
            Continue:('$Data(props(tAttr)))
            If (props(tAttr)'=$Get(tMap(tAttr,"default"))) {
	            If tAttr="MatchRoles",props(tAttr)[("%DB_"_$Namespace) Set props(tAttr)=$Replace(props(tAttr),("%DB_"_$Namespace),"${dbrole}") ##; 149
                Set ..TemplateResources(tAppName,$Get(tMap(tAttr)))=props(tAttr)
            }
        }
    }
    Return $$$OK
}

**Comment by SergeyMi37** [comment]
this is implemented i think it can be closed ?
