### ISSUE TITLE
Introduce an option to copy files to the server without creating a web app

### ISSUE THREAD

**Issue by evshvarov** [intersystems/ipm#156]
E.g. we need to copy dsw config json file to a certain place (in dsw folder) on iris server

**Comment by isc-tleavitt** [comment]
There's a FileCopy resource processor just for this. Needs to be documented.

**Comment by isc-dchui** [comment]
Added documentation here:
https://github.com/intersystems/ipm/wiki/03.-IPM-Manifest-(Module.xml)#filecopy
