### ISSUE TITLE
Support for INT routines in ZPM

### ISSUE THREAD

**Issue by chrisemunt** [intersystems/ipm#176]
It would be great to have direct support for INT routines in ZPM as a lot of older packages will be written that way and for many low-level coding tasks there’s not really any advantage to creating routines as MACs.  It's currently possible to work around this limitation as follows.

First export the INT routine to a file with a MAC extension (in the project's /src/mac/ directory). 

USER>d $system.OBJ.Export("myroutine.int","c:\myproject\src\mac\myroutine.mac")

Then edit the export file (myroutine.mac in the case), changing type="INT" to type="MAC".

<?xml version="1.0" encoding="UTF-8"?>
<Export generator="IRIS" version="26">
<Routine name="myroutine" type="MAC" languagemode="0"><![CDATA[ etc .............

This works to the extent that ZPM will successfully import the routine but it would be good to have direct support for INTs.

**Comment by daimor** [comment]
No, no reason to support int code. No matter how much old is this code. It should be replaced with Mac code. There are no reasons to stay with int code anyway.

**Comment by daimor** [comment]
What do you mean by low-level code, and why it's better to have int code there?

**Comment by evshvarov** [comment]
@Dmitriy Maslennikov <mrdaimor@gmail.com> let's see how many votes it gets.

**Comment by evshvarov** [comment]
@chrisemunt  - if you could provide the example of repo where INT will have preference over MAC?

**Comment by chrisemunt** [comment]
An example GitHub repo I have in mind is here (mgsi), going straight to a directory holding INT routines ...

https://github.com/chrisemunt/mgsi/tree/master/m

I'm happy for this to remain the master repository for this project.  Yes, I could rework these as MAC routines, but I'm not going to.  So, the question is really this: do you want developers like me to use ZPM or not.

**Comment by evshvarov** [comment]
https://github.com/chrisemunt/mgsi/blob/master/m/zmgsi.ro: This is not INT
;)

**Comment by daimor** [comment]
Chris, there, what you shared is int but in RO format, it's not acceptable anyway. ZPM is for IRIS mostly, there we already have better format for files, and MAC routines is the best way for it, as it's exactly the same way is looks in Studio and acceptable in VSCode, so you can edit it as is.

**Comment by chrisemunt** [comment]
Indeed it's not ... it's actually two routines (%zmgsi, %zmgsis) output in the old %RO format - which gives you some idea as to the vintage of this stuff (and me!).  In fact, all 4 files in that folder contain just these two routines but in different save formats depending on whether the user downloading them has Cache or IRIS.  To my mind, the ZPM project is good thing and an opportunity to make things easier for developers and consumers and should not be about ideology.  The reality is that all InterSystems databases support INT and MAC routines so I see no reason why the InterSystems package manager shouldn't support them both.

**Comment by daimor** [comment]
Take it as an attempt to be in the future, and just leave the past in the past. Any old-school staff, which may be replaced with a modern better way, have to be replaced so. How we are going to move forward with all of this old-school staff?
