### ISSUE TITLE
Introduce a license field for a ZPM package

### ISSUE THREAD

**Issue by evshvarov** [intersystems/ipm#201]
and license info for the installed module

**Comment by SergeyMi37** [comment]
Isn't this a solution to the problem?
      <Author>
        <Person>your name</Person>
        <Organization>your organization</Organization>
        <CopyrightDate>2020</CopyrightDate>
        <License>MIT</License>
        <Notes>notes</Notes>
      </Author>

**Comment by SergeyMi37** [comment]
![image](https://user-images.githubusercontent.com/18187317/142852654-a83d2ff5-ffe5-4bbf-9dbf-655381342c9d.png)

this is implemented i think it can be closed
