### ISSUE TITLE
make global resources less complex

### ISSUE THREAD

**Issue by evshvarov** [intersystems/ipm#234]
Now if you want to include the global X in resources you need:
place the file in:
/src/gbl/X.XML

and add the resource:
<Resource Name="X.GBL" />

Ideally to have the option to describe globals as XML too, like:
<Resource Name="X.XML" />
because it's not clear why the resource is GBL and the file is XML.
or support the GBL extension.

**Comment by isc-tleavitt** [comment]
The intended workflow around this needs better documentation.

**Comment by isc-dchui** [comment]
Added example in documentation here:
https://github.com/intersystems/ipm/wiki/03.-IPM-Manifest-(Module.xml)#globals-resource-example
