### ISSUE TITLE
Make sure that when updating zpm, the setting for the current repository is not reset

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems/ipm#244]

**Comment by SergeyMi37** [comment]
Additionally, all states of the config parameters remained the same

**Comment by isc-tleavitt** [comment]
@isc-shuliu see ZPM.Installer:ZPMInit - we don't want to overwrite any old/existing settings here.

**Comment by isc-tleavitt** [comment]
Closing issues fixed in v1 branch for cleaner bookkeeping.
