### ISSUE TITLE
SQL query param always null

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/ipm#261]
https://github.com/intersystems-community/zpm/blob/df32a6d798b90de64ae2700cb545976551a6c5a1/src/cls/_ZPM/PackageManager/Client/Manager.cls#L54

This query uses `registry` variable which is ProcedureBlock private so will always evaluate to null in `%SQL.Statement.bindArguments`.  This seems to be the desired behavior since this method is invoked during `zpm install` to search all repositories, so "fixing" this would break install unless the `SearchCriteria` for install is also updated to remove this line:

https://github.com/intersystems-community/zpm/blob/df32a6d798b90de64ae2700cb545976551a6c5a1/src/cls/_ZPM/PackageManager.cls#L1459

**Comment by isc-tleavitt** [comment]
I think this was the real issue behind #331

**Comment by isc-tleavitt** [comment]
Closing issues fixed in v1 branch for cleaner bookkeeping.
