### ISSUE TITLE
SQL API

### ISSUE THREAD

**Issue by bdeboe** [intersystems/ipm#264]
ZPM with its own command line and ObjectScript API (well, kind of) is very practical already, but we also (may) cater to an audience that's looking at IRIS as a relational database and uses SQL and nothing but SQL to access it. For this audience, ZPM remains an equally useful mechanism to pull in additional modules (after initial setup) and a basic SQL API for installing and listing modules may only be a small piece of dev work.

```SQL
CALL %ZPM.Install('Samples-BI')
```

The one thing I ran into while taking a stab at this myself was that ZPM is really verbose, and saving the output to the [spool device](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GIOD_spool) in order to save it to some log table was prevented by the frequent namespace switches in various helper methods.

**Comment by isc-tleavitt** [comment]
I'm going to say no on this, because it turns any almost-innocent SQL injection vulnerability an an almost-innocently misconfigured system into a catastrophe.
