### ISSUE TITLE
zpm "install packagename -DPermitDowngrade=1" doesn't work

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/ipm#356]
For example:
```
USER>zpm "install zpm 0.4.x -DPermitDowngrade=1"
 
ERROR! Cannot downgrade zpm from version 0.5.1 to 0.4.0
```

Root cause: %ZPM.PackageManager.Developer.Utils:LoadModuleReference looks for this flag in pParams("PermitDowngrade"), but now it's shifted to pParams("zpm","PermitDowngrade")

There may be other cases of the same issue as well - should review the codebase for them.

**Comment by isc-shuliu** [comment]
This issue has already been fixed

**Comment by isc-tleavitt** [comment]
(note: has been fixed in the v1 branch, not yet in master)

**Comment by isc-shuliu** [comment]
Somehow this becomes an issue again. `%ParseCommandInput()` ignores the `-DPermitDowngrade` option.

**Comment by isc-shuliu** [comment]
It turns out to be caused by my local dev setup. Closing.
