### ISSUE TITLE
installing zpm on system with other NLS locale than enuw

### ISSUE THREAD

**Issue by dkutac** [intersystems/ipm#362]
when installing zpm on a system with NLS locale different that 'enuw', e.g. 'csyw' you may receive an error "module.xml contains multiple documents." If this happens to you, temporarily set your NLS locale to 'enuw', install zpm again. It shall now install. Then you can switch NLS locale to your original one.

**Comment by isc-tleavitt** [comment]
This was fixed in https://github.com/intersystems/ipm/pull/411
