### ISSUE TITLE
Add the ability to restrict the installation to IRIS or IRIS for Health platform to the requirement attribute

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems/ipm#364]
Add the ability to restrict the installation to IRIS or IRIS for Health platform to the requirement attribute

**Comment by isc-tleavitt** [comment]
@isc-shuliu some guidance here:
See %IPM.Storage.SystemRequirements
Consider adding integration tests with new package definitions under tests/integration_tests/Test/PM/Integration/_data to cover the use cases.
Recommended syntax - see https://github.com/intersystems/ipm/wiki/03.-IPM-Manifest-(Module.xml)#elements :

Requires IRIS for Health (implies Interoperability="enabled"):
`<SystemRequirements Version=">=2020.1" Health="true" />`

Requires IRIS (not IRIS for Health) with non-health interoperability:
`<SystemRequirements Version=">=2020.1" Interoperability="enabled" Health="false" />`

Default behavior: we don't care.
