### ISSUE TITLE
Fails to install on IRIS 2023.1 Dev Preview (build 207U)

### ISSUE THREAD

**Issue by PYDuquesnoy** [intersystems/ipm#376]
When trying to import v0.5.2 from Studio, or loading with $SYSTEM.OBJ.Load() it fails.
Error is:
Load finished successfully.
2023-03-07 10:36:36 0 %ZPM.Installer: ERROR #5001: Could not find %ZLANGC00 routine contents in %ZPM.PackageManager

**Comment by daimor** [comment]
Yes, due to changes in 2023.1, version 0.5.2 and earlier not compatible with it, check the latest betas, until the final release

**Comment by PYDuquesnoy** [comment]
Thank you Dmitry for such a prompt reply, I installed 0.5.3-beta.2 and it worked like a charm!
