### ISSUE TITLE
IPM installation take very long the first time

### ISSUE THREAD

**Issue by isc-mzhou** [intersystems/ipm#378]
I am using IPM to install and update supply chain framework on my local IRIS instance. I noticed very frequently, when I run an install command, it often stuck for a very long time (I usually had to cancel it with Ctl-C and restart the install). If I cancel it and repeat the install command, it finished really fast.
![image](https://user-images.githubusercontent.com/92470455/225977729-c3fad0ed-8234-4338-84fd-32225b45dfd3.png)

**Comment by daimor** [comment]
Could you try to reproduce it with active verbose flag '-v'

**Comment by gjsjohnmurray** [comment]
Maybe #267

**Comment by isc-rkuszews** [comment]
@isc-mzhou Is this resolved?  If so, can you close this issue?  Otherwise, can you let us know what's going on?

**Comment by isc-tleavitt** [comment]
I think this is most likely distinct from #267. @isc-mzhou if you could use a hand with %SYS.MONLBL to diagnose the slowness just let me know, I can help or someone from my team can.

**Comment by isc-mzhou** [comment]
I had the problem with my Dell PC. Recently I moved a Mac, and have not seen this problem on my Mac yet. Guess we can close this issue for now, and re-open it if I experience the problem again.
