### ISSUE TITLE
container start fails

### ISSUE THREAD

**Issue by rcemper** [intersystems/ipm#394]
D:\GitHub\ipm>docker-compose up
[+] Running 1/1
 ✘ registry Error                                                                                            0.5s
Error response from daemon: Head "https://docker.pkg.github.com/v2/intersystems-community/zpm-registry/zpm-registr
y/manifests/latest": no basic auth credentials

**Comment by daimor** [comment]
'docker-compose build registry' does not help?

**Comment by rcemper** [comment]
NO !
**docker-compose build registry** just does nothing
BUT **docker-compose build** 
D:\GitHub\ipm>docker-compose build
[+] Building 0.5s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                         0.1s
 => => transferring dockerfile: 477B                                                                         0.0s
 => [internal] load .dockerignore                                                                            0.0s
 => => transferring context: 2B                                                                              0.0s
 => [internal] load metadata for containers.intersystems.com/intersystems/irishealth-community:2022.2.0.368  0.3s
 => [internal] load build context                                                                            0.1s
 => => transferring context: 29.69kB                                                                         0.1s
 => [stage-0 1/2] FROM containers.intersystems.com/intersystems/irishealth-community:2022.2.0.368.0@sha256:  0.0s
 => CACHED [stage-0 2/2] RUN --mount=type=bind,src=.,dst=/home/irisowner/zpm/   iris start iris &&   iris s  0.0s
 => exporting to image                                                                                       0.0s
 => => exporting layers                                                                                      0.0s
 => => writing image sha256:dad80c7c3d75a2425b1e095fe1a7878860a91d3307115a9805a1ed927b98b76a                 0.0s
 => => naming to docker.io/library/ipm-iris                                                                  0.0s                                                   

D:\GitHub\ipm>docker-compose up
[+] Running 1/1
 ✘ registry Error                                                                                            0.7s
Error response from daemon: Head "https://docker.pkg.github.com/v2/intersystems-community/zpm-registry/zpm-registr
y/manifests/latest": no basic auth credentials

D:\GitHub\ipm>

**Comment by rcemper** [comment]
**full version**

D:\GitHub\ipm>docker compose build --progress plain
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 477B done
#2 DONE 0.1s

#3 [internal] load metadata for containers.intersystems.com/intersystems/irishealth-community:2022.2.0.368.0
#3 DONE 0.9s

#4 [stage-0 1/2] FROM containers.intersystems.com/intersystems/irishealth-community:2022.2.0.368.0@sha256:ad1e47b5
005644a6db55b599a5f08e4f68cb827758993a89680ac9af35fbb0c1
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 29.69kB 0.1s done
#5 DONE 0.1s

#6 [stage-0 2/2] RUN --mount=type=bind,src=.,dst=/home/irisowner/zpm/   iris start iris &&   iris session iris "##
class(%SYSTEM.OBJ).Load("/home/irisowner/zpm/Installer.cls","ck")" &&   iris session iris "##class(%ZPM.Installer)
.setup("/home/irisowner/zpm/",3)" &&   iris stop iris quietly
#6 CACHED

#7 exporting to image
#7 exporting layers done
#7 writing image sha256:dad80c7c3d75a2425b1e095fe1a7878860a91d3307115a9805a1ed927b98b76a done
#7 naming to docker.io/library/ipm-iris done
#7 DONE 0.0s

D:\GitHub\ipm>
