### ISSUE TITLE
Need examples for the usage of libdir and other variables

### ISSUE THREAD

**Issue by ghost** [intersystems/ipm#396]
Will it be possible to add more examples and/or documentation regarding the use of variables like libdir, how their values are set, and how to use them correctly?
This will save everyone time by not having to work through all the code to try and see its relevance and how to use it.

**Comment by isc-dchui** [comment]
Added a section to the wiki here:
https://github.com/intersystems/ipm/wiki/03.-IPM-Manifest-(Module.xml)#system-expressions
