### ISSUE TITLE
Stop and Start of Interoperability Production

### ISSUE THREAD

**Issue by csoft-sc** [intersystems/ipm#399]
With complex deployments of applications you may wish to stop the production at specific times and start it only after the configuration has been completed.

**Comment by daimor** [comment]
There is <Invoke>, which can help with it, it accepts attributes 
* Phase (https://github.com/intersystems/ipm/blob/5a5f5f428667d353393e5254a5fc5a63f175d14d/src/%25ZPM/PackageManager/Developer/Lifecycle/Base.cls#L6) - default Configure
* When - Before, After

So, Using Phase="Reload" When="Before" to stop production, and Phase="Configure" When="Before" to start it back

**Comment by csoft-sc** [comment]
Thank you.

Kind regards,

[upload image]
Stefan Cronje
Director
comprehensoft
M: +27 82 641 1478
W: https://www.comprehensoft.com<https://www.comprehensoft.com/>
E: ***@***.******@***.***>
[linkedin]<https://www.linkedin.com/company/comprehensoft>

IMPORTANT: The contents of this email and any attachments are confidential. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by csoft-sc** [comment]
I am looking through the code, but not finding anything indicating how this will work
Is on type "Resousrce"?
Or do you mean I should use Invoke with these attributes?

**Comment by evshvarov** [comment]
Yes, invoke tag with phase attribute

**Comment by daimor** [comment]
Something like this
```
  <Invoke Class="Ens.Director" Method="StopProduction" Phase="Reload" When="Before" CheckStatus="1"/>
  <Invoke Class="Ens.Director" Method="StartProduction" Phase="Configure" When="Before" CheckStatus="1">
    <Arg Value="My.Production"/>
  </Invoke>

```
