### ISSUE TITLE
Issue in data import via IPM 

### ISSUE THREAD

**Issue by evshvarov** [intersystems/ipm#438]
There is an option to transfer files and import it then via IPM. E.g. in this [package](https://github.com/intersystems-community/iris-fhir-template), that can setup a FHIR server and load test data via:
zpm "install fhir-server"

But it fails to load data due to transaction mode in IPM, investigated by @daimor 
Current workaround is to install in a dev mode:
zpm "install fhir-server -dev"

or load from GitHub directly:
zpm "load Github URL"

Also the issue [filed](https://github.com/intersystems-community/iris-fhir-template/issues/22) in the package

**Comment by isc-tleavitt** [comment]
Installing with `-DNoTransaction=1` would work too.

The point of wrapping package installation in a transaction is to ensure that if installation fails, it's undone. We don't want to give an individual package a way to bypass this. A generalized solution to #439 to allow an Invoke to happen outside of the transaction, after installation has fully completed, would address this need as well; for now it's up to either documentation of install steps (using `-dev` or `-DNoTransaction=1`) or a package-level workaround.
