### ISSUE TITLE
ZPM does not work with DelimitedIdentifiers SQL parameter set to 0

### ISSUE THREAD

**Issue by bg-ssh** [intersystems/ipm#440]
USER>d $SYSTEM.SQL.Util.SetOption("DelimitedIdentifiers",0)

USER>zpm "install zpmhub"

ERROR! SQLCODE: -25 Message:  Input (?) encountered after end of query^ SELECT DISTINCT %EXACT Dependencies_VersionString ?

**Comment by isc-tleavitt** [comment]
Closing issues fixed in v1 branch for cleaner bookkeeping.
