### ISSUE TITLE
IRIS 2023.1.3 Illegal Regular SQL identifier 'Module'

### ISSUE THREAD

**Issue by vicssun** [intersystems/ipm#441]
Error on importing/compiling zpm-0.7.0.xml stating that 'Module' is a SQL reserved word.

**Comment by vicssun** [comment]
I believe this error is related to my customer's disabling of "support delimited identifiers"

**Comment by isc-tleavitt** [comment]
This is a duplicate of #440 (maybe actually the same root case, given that the two were reported the same day?). There may be a number of side effects related to this, but it boils down to "IPM should work with 'support delimited identifiers' disabled"
