### ISSUE TITLE
show install date with list action

### ISSUE THREAD

**Issue by SCanzano** [intersystems/ipm#486]
when I use the list command to show the modules that have been installed , which shows this

`
zpm:HSCUSTOM>list
rclib-rcipm          1.0.6
rclib-unittest       1.0.2
rclib-rcreportsbasic 1.0.2
rclib-rdm            1.0.1
rclib-system         1.0.2
rclib-rcdlf          1.0.1
rclib-ens            1.0.4
rclib-enslib         1.0.3
rclib-fhir           1.0.1

zpm:HSCUSTOM>
`
I would like some way to either show the install date via a flag or always show the date upon which the module was installed

**Comment by isc-tleavitt** [comment]
This relates to #366 - we don't have the data to back this now, but #366 would provide it and exposing it in "list" with a flag would make a lot of sense.
