### ISSUE TITLE
Improve parsing of load path

### ISSUE THREAD

**Issue by isc-shuliu** [intersystems/ipm#487]
When running `zpm "load <path>"`, [the code](https://github.com/intersystems/ipm/blob/9978352e58b9926ce0ad0dd115f0edb16c99ed68/src/%25IPM/Main.cls#L1417) checks for whether `<path>` starts with http (a git repo) or not (local dir or tarball). 

While this is sufficient in almost all cases, a user might inadvertently parse in a relative path starting with http (w.r.t. `<IRISROOT>/mgr/`). A safer way is to check for prefix `http://` and prefix `https://`.

**Comment by isc-tleavitt** [comment]
@isc-shuliu you might see `%Net.URLParser` for this.
