### ISSUE TITLE
Default resource processor ignores percent (%) in path

### ISSUE THREAD

**Issue by isc-shuliu** [intersystems/ipm#490]
The [default behaviour](https://github.com/intersystems/ipm/blob/b7ea8fa75f902fbfe7b2a20acc96321eba1e5020/src/cls/IPM/ResourceProcessor/Default/Document.cls#L32) of resource processor is to ignore percent (%) in resource paths.

It seems to be a problem for some legacy packages such as [zapm](https://github.com/SergeyMi37/zapm/blob/3b442780b65de5b7f837d28d472457b315df8446/module.xml#L16). 

@isc-tleavitt I wonder what is the rationale behind this convention to ignore "%" by default and if there is a way around it for package publishers (other than renaming their directory).

**Comment by isc-tleavitt** [comment]
@isc-bzhang @isc-kiyer do you have background on this?

IIRC we're permissive on load and will support it with/without the % depending on what happens to exist on disk.

**Comment by isc-shuliu** [comment]
It seems [this code](https://github.com/intersystems/ipm/blob/b7ea8fa75f902fbfe7b2a20acc96321eba1e5020/src/cls/IPM/ResourceProcessor/Default/Document.cls#L88) is trying to find whatever exists on filesystem, but the [later call](https://github.com/intersystems/ipm/blob/b7ea8fa75f902fbfe7b2a20acc96321eba1e5020/src/cls/IPM/ResourceProcessor/Default/Document.cls#L127) to $TRANSLATE defeats this purpose.
