### ISSUE TITLE
Expand packages CI workflow to cover *all* packages

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/ipm#500]
We'll end up adding more things to #475 as a result. @isc-shuliu found one issue in an InterSystems package that escaped the existing workflow - we'll want to expand eventually anyway, so let's just do it now!

**Comment by isc-shuliu** [comment]
There are a total of 32 jobs that are passing in master but not in v1:
- [ ] alwo-enshelper
- [ ] alwo-goselector
- [ ] alwo-ompare
- [ ] alwo-sendcomplexmessagefromservice
- [ ] alwo-unittest-ruleset-bulkprofile
- [ ] appmsw-banks-ru
- [ ] appmsw-sql2xlsx
- [ ] bg-appealai
- [ ] demo-pandas-analytics
- [ ] evshvarov-covid19-analytics
- [ ] fhir-server
- [ ] foreign-table
- [ ] glassdoor-reviews
- [ ] health-harbour
- [ ] interoperability-for-money
- [ ] interopway
- [ ] iris-fhirfy
- [ ] iris-flow
- [ ] iris-health-coach
- [ ] iris-medicopilot
- [ ] iris-vectorlab
- [ ] irischatgpt
- [ ] isc.ipm.js
- [ ] isc.json
- [ ] java-global-editor
- [ ] nacl-jv
- [ ] samples-bi
- [ ] telegram-gpt
- [ ] vscode-snippets-john.murray-example
- [ ] zbash
- [ ] zpip
- [ ] zpm-generate-ui

In the meantime, there are 21 jobs that are passing in v1 but failing on master
- [ ] analytics-okr
- [ ] cloudstudio
- [ ] cmpurgebackup
- [ ] code-compare
- [ ] collection-index-and-query
- [ ] healthcare-hl7-xml
- [ ] ifindportal
- [ ] ijc-demo
- [ ] iknow-utils
- [ ] imageaicreator
- [ ] imagesearchvideo
- [ ] import-csv-update-sql
- [ ] initecp
- [ ] iris-history-monitor
- [ ] iris-image-index-demo
- [ ] iris-image-verctor-search
- [ ] iris-imap-python-adaptor
- [ ] iris-internal-websocket-client
- [ ] jirisreport
- [ ] realworld
- [ ] restoreui

**Comment by isc-tleavitt** [comment]
vscode-snippets-john.murray-example
ERROR! ObjectScript error: <CLASS DOES NOT EXIST>doInvoke+5^%IPM.Storage.InvokeReference.1 *%Z.IPM.Bootstraps.Main

The issue here seems to be that IPM doesn't actually compile the class.

**Comment by isc-tleavitt** [comment]
This is all working now, going to create a followup issue to automate summarization.
