### ISSUE TITLE
Conflicts between packages due to inconsistent casing

### ISSUE THREAD

**Issue by isc-shuliu** [intersystems/ipm#534]
@isc-tleavitt @isc-kiyer 

In ObjectScript,  there are error codes (5092, 5093) for packages/classes sharing otherwise the same name except for casing. In the current community registry, we already have such problem. For example, package `csvgen` is under package `community` and package `demo-pandas-analytics` is under `Community`. This makes `csvgen` and `demo-pandas-analytics` not compatible in the same environment. But such incompatibility is really unnecessary and should be fixed.

Some ideas:
* Should we implement a warning when user publishes a package? 
* Maybe advocate/enforce a naming convention? 
* Even better, can we make the package name parametrizable?

See also #527

**Comment by isc-tleavitt** [comment]
The most we can do in a community setting is advocate a naming convention.
