### ISSUE TITLE
IRIS 2024.2 on Windows no longer ships irispip.exe

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/ipm#540]
https://github.com/intersystems/ipm/blob/5a4e85ff129573e6337ab205fc07946859bf3e33/src/%25ZPM/PackageManager/Developer/Lifecycle/Base.cls#L526

See also https://github.com/caretdev/irislab/issues/1

**Comment by isc-tleavitt** [comment]
Fixed via #538 (v1) and #543 (master) - will be in next (soon!) release

**Comment by gjsjohnmurray** [comment]
> will be in next (soon!) release

@isc-tleavitt Any sign of this?

**Comment by isc-tleavitt** [comment]
@gjsjohnmurray thanks for the reminder. We've been focusing on the next major release and lost sight of this.
