### ISSUE TITLE
Exclude prereleases from SemVer range maximums

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/ipm#557]
Per e.g. https://github.com/npm/node-semver?tab=readme-ov-file#x-ranges-12x-1x-12- / https://github.com/npm/node-semver/commit/059a5adec5aefaa764bf4fdb717ae8b42cbbefcd - we need to exclude prereleases from range maximums as a rule. The simple way to do this is representing a range maximum with a prerelease of 0 (e.g., 1.x becomes >=1.0.0 <2.0.0-0).

See discussion in https://github.com/intersystems-community/zpm-registry/issues/91

I'd recommend a test-driven development workflow for this, expanding on the existing SemVer unit tests. This is v0.9.0 critical.

**Comment by isc-shuliu** [comment]
@isc-tleavitt 

In node-semver, certain expansion/comparisons depends on the value of `includePrerelease` tag. In IPM, we have so far assumed this tag is `false`. Namely,
* Version `1.5.0-beta` does not satisfy expression `1.x`
* Version `2.3.4-beta` does not satisfy expression `>=2`

Shall we keep this behavior or add an additional argument `pIncludePrerelease` in ` %IPM.General.SemanticVersionExpression.Comparator::Evaluate()`?

**Comment by isc-shuliu** [comment]
Fixed by #559
