### ISSUE TITLE
Automatically create role for reading routine DB in WebApplication

### ISSUE THREAD

**Issue by isc-shuliu** [intersystems/ipm#564]
See https://github.com/intersystems/ipm/pull/562#issuecomment-2344012005 and https://github.com/intersystems/ipm/pull/562#issuecomment-2343662304

We should allow a syntax (such as `${codeReadRole}`) in WebApplication resource. IPM should create this role (if nonexistent) and set add this role to the WebApplication.

**Comment by isc-tleavitt** [comment]
@isc-shuliu thanks for spinning this out as a new issue - I agree that's most appropriate.

**Comment by isc-shuliu** [comment]
After discussion with @isc-kiyer , it's best to create a `<Role>` resource instead of using a ${codeReadRole}. Will close this one.
