### ISSUE TITLE
Update datatypes in old CSPApplication resource processor

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/ipm#588]
To account for an upcoming IRIS change slated for 2025.1 (internal ref: DP-433607 / JYN026) we need to update %IPM.ResourceProcessor.CSPApplication (in v1 - this is appropriate for 0.9.0) and its legacy %ZPM counterpart (in master) to give DeepSeeEnabled and iKnowEnabled type %Installer.Boolean instead of %Boolean.

**Comment by isc-kiyer** [comment]
@isc-tleavitt I think CSPApplication should be deleted altogether in favor of WebApplication for the v1 release. That processor has no side effects (copying files) and is robust to changes in IRIS.

**Comment by isc-tleavitt** [comment]
@isc-kiyer I don't like the compatibility impact. We have a lot of community packages that use CSPApplication.

**Comment by isc-kiyer** [comment]
@isc-tleavitt Hmm can we at least mark it as deprecated somehow?

**Comment by isc-tleavitt** [comment]
@isc-kiyer yes, we should certainly do that. @isc-shuliu please tackle that as part of the v1 PR for this.
