### ISSUE TITLE
%IPM_Repo_Filesystem.Cache is out of sync and causing errors - how to clear out and start fresh

### ISSUE THREAD

**Issue by chi-leadnorth** [intersystems/ipm#596]
Version: zpm-0.9.0-beta
On a new install of IPM and attempting first module installation. 

Getting this error upon zpm repo call: 
`ERROR! SQLCODE: -106 Message: Delete row from table '%IPM_Repo_Filesystem.Cache' with %rowid1' failed, row with this id was not found.
`

Also getting it when attempting to delete the repo. 
In the backend, it appears the repo was recorded in: 
%IPM_Repo_Filesystem.Definition and %IPM_Repo.Definition without corresponding row in %IPM_Repo_Filesystem.Cache.
The foreign key constraints prevent me from cleaning the Definitions to try to clear the error. 

How can I clear these tables to start anew?

**Comment by isc-tleavitt** [comment]
@chi-leadnorth thank you so much for trying it out and letting us know you hit this. To clarify, did you previously have IPM 0.7.x running on the instance? What's the specific zpm repo call you're using?

@isc-shuliu can you look into this as a top priority?

**Comment by chi-leadnorth** [comment]
I did not have IPM 0.7.x. I encountered an error regarding the LoadStream call when trying to install IPM 0.7.x. Attempted beta on a lark and saw that it worked, so I moved forward with that. Trying to "downshift" back to loading 0.7.x but system is fighting me on that. 

More insight -- I see that the backend globals for %IPM_Repo_Filesystem.Cache are populating, but from SQL, selecting from the table shows no rows, but does throw this error:   [SQLCODE: <-350>:<An unexpected error occurred executing SqlComputeCode>]

  [%msg: <Unexpected error executing SqlCompute code for field 'Version_Postrelease': <UNDEFINED>%0AmBk1+18^%sqlcq.DPTNS.cls14.1 *Prerelease>]

**Comment by chi-leadnorth** [comment]
> @chi-leadnorth thank you so much for trying it out and letting us know you hit this. To clarify, did you previously have IPM 0.7.x running on the instance? What's the specific zpm repo call you're using?

zpm "repo -name DPTRepo2024 -snapshots 1 -fs -depth 2 -path /share/LN/DPT_2024"

**Comment by isc-shuliu** [comment]
Hi @chi-leadnorth, can you also share with us your IRIS version info?
```objectscript
Write $ZV
```

**Comment by chi-leadnorth** [comment]
> Hi @chi-leadnorth, can you also share with us your IRIS version info?
> 
> ```objectscript
> Write $ZV
> ```

IRIS for UNIX (Red Hat Enterprise Linux 8 for x86-64) 2023.1.2 (Build 450_0_23376U) Wed Apr 24 2024 00:00:42 EDT

**Comment by chi-leadnorth** [comment]
Also - in case this helps -- the module I am trying to install is an early release - the HL7 Data Profiling Tool. In case the pre-release status is what is causing the issue on the Sql compute

**Comment by isc-shuliu** [comment]
> Also - in case this helps -- the module I am trying to install is an early release - the HL7 Data Profiling Tool. In case the pre-release status is what is causing the issue on the Sql compute

That's likely related to the problem. Can you share with me the version string of the module you're installing? I'm trying to reproduce the error but haven't had any luck so far.

**Comment by isc-shuliu** [comment]
Actually I just reproduced it :) Looking into the cause now

**Comment by isc-shuliu** [comment]
Just identified the bug and implemented the fix in #599

**Comment by isc-shuliu** [comment]
@chi-leadnorth We have a new IPM v0.9.0-beta.27 release published. Can you try to reload the associated xml file, restart your iris instance, and see if you can remove all repos using `zpm "repo -delete-all"`?

**Comment by chi-leadnorth** [comment]
The new release resolved the issue. Thank you kindly!
