### ISSUE TITLE
Add support for creating a namespace and installing a module into it in a single command

### ISSUE THREAD

**Issue by isc-eneil** [intersystems/ipm#629]
Per discussions with HSOPS, we're asking for the possibility of creating a namespace and corresponding database into which a module can be installed as part of the same command that loads/installs the module. The namespace name, global, routine, and code database names and locations should all be configurable by the user via flat file.

**Comment by isc-tleavitt** [comment]
This issue goes away with CPF merge as the language for configuration, using https://docs.intersystems.com/iris20243/csp/docbook/DocBook.UI.Page.cls?KEY=RACS_execute to call in to IPM.
