### ISSUE TITLE
Add support for installing multiple modules in a single command

### ISSUE THREAD

**Issue by isc-eneil** [intersystems/ipm#630]
Per conversations with HS, we are asking for support for installing and loading multiple modules onto an instance via a single install or load command. It should be possible for the user to specify the namespace into which each module should be installed, ideally via flat file.

This will allow for a "solution pack" that is comprised of several modules to be easily installed.

**Comment by isc-tleavitt** [comment]
Likely minor complication here is going to be unified dependency resolution across the set of modules.

**Comment by isc-tleavitt** [comment]
Note from @isc-kiyer in discussion today: most important use case is the flat file multi-namespace orchestration

**Comment by isc-eneil** [comment]
Note that this is less urgent than the other HS-requested issues because we could ask users to run an install/load command for each module.

**Comment by evshvarov** [comment]
Why not manage it via dependencies? e.g. having a "master" module that have
a list of dependent modules?

**Comment by isc-tleavitt** [comment]
Going to have CPF merge drive this, so nothing needed in IPM.
