### ISSUE TITLE
additional flags for pip should be able to be specified

### ISSUE THREAD

**Issue by isc-tdyar** [intersystems/ipm#646]
When installing python packages, ZPM allows some options to be set, but pip has many flags. Recently, a developer found that the sentence-transformers package results in a very large docker image (GBs), and one suggestion is to use pip's "--no-cache-dir" flag that reducews disk usage by not caching installation files. It would be great if ZPM had a "additionalPipFlags" config setting, that would allow more customization of the pip command.

**Comment by isc-tleavitt** [comment]
@isc-shuliu this would be super easy to implement and impactful, especially for GenAI use cases.

**Comment by isc-shuliu** [comment]
@isc-tdyar 
That's a great idea! In the meantime, most, if not all, of `pip`'s flags have their corresponding environment variables. For example, `--no-cache-dir` can be replaced with setting `PIP_NO_CACHE_DIR`. 

This can be useful when install dependencies requiring python dependencies. As a side question, is there another way to pass modifiers/data to the `pCommandInfo` of dependencies? @isc-tleavitt
