### ISSUE TITLE
Steps for changing default repo branch

### ISSUE THREAD

**Issue by isc-shuliu** [intersystems/ipm#651]
Once the all package workflow passes, we'll change the default branch.

1. Rename the current `v1` branch to `v0.9.x` and make it default
2. Rename the current `v1-next` branch to `v0.10.x`. Also merge all `v0.9.x` changes into `v0.10.x`
3. Rename the current `master` branch to `v0.7.x`. 
4. Update CIs to reflect new branch names
5. Detangle the changeling between `v0.9.x` and `v0.10.x`

Every future minor version should have its own branch, and we can change the default branch without renaming the branch when promoting a version.

**Comment by isc-shuliu** [comment]
@isc-tleavitt 

Do the following renaming steps sound good?

1. `v1` $\longrightarrow$ `v0.9.x` (new default branch)
2. `v1-next` $\longrightarrow$ `v1.0.x`
3. `master` $\longrightarrow$ `v0.7.x`

**Comment by isc-tleavitt** [comment]
v1-next should be v0.10.x but otherwise good

**Comment by isc-tleavitt** [comment]
@isc-shuliu actually one more thing, I missed this:
**We want the default branch to be "main"** which should just be == v0.9.x for now.
After we release v0.9.0 and have a burn-in period to possibly release critical bugfixes (no later than 1/8, we'll say) we should merge v0.10.x to main and have that as the target of PRs.

**Comment by isc-tleavitt** [comment]
Also need to update main.yml to release from the "main" ref rather than "master"

**Comment by isc-shuliu** [comment]
@isc-tleavitt 
Fixed by 5025c10eea36006a69f935b23195c979ef7bc4f7 and abd9f796caa42028decf00470ee867f7ea5718f6
